// This source file was generated by Fungo. DO NOT MODIFY.
//
// Generated on: 2019-09-17 10:06:29
// Fungo version: 0.0.1

package find_last

func FindLast(items []string, predicate func(string) (bool, error)) (int, string, error) {
	for i := len(items) - 1; i >= 0; i-- {
		res, err := predicate(items[i])
		if err != nil {
			return i, items[i], err
		}
		if res {
			return i, items[i], nil
		}
	}
	var emptyVal string
	return -1, emptyVal, nil
}