// This source file was generated by Fungo. DO NOT MODIFY.
//
// Generated on: 2019-09-17 10:06:29
// Fungo version: 0.0.1

package max

import "errors"

func Max(items []int, comparison func(int, int) (int, error)) (int, error) {
	var max int
	if len(items) == 0 {
		return max, errors.New("slice contains no items")
	}
	max = items[0]
	for i := 1; i < len(items); i++ {
		res, err := comparison(items[i], max)
		if err != nil {
			return max, err
		}
		if res > 0 {
			max = items[i]
		}
	}
	return max, nil
}