// This source file was generated by Fungo. DO NOT MODIFY.
//
// Generated on: 2019-09-17 09:20:22
// Fungo version: 0.0.1

package group_by

func GroupBy(items []string, calculation func(string) (string, error)) (map[string][]string, error) {
	groups := make(map[string][]string)
	for _, item := range items {
		res, err := calculation(item)
		if err != nil {
			return groups, err
		}
		if _, ok := groups[res]; !ok {
			groups[res] = make([]string, 20)
		}
		groups[res] = append(groups[res], item)
	}
	return groups, nil
}