// This source file was generated by Fungo. DO NOT MODIFY.
//
// Generated on: 2019-09-17 10:18:50
// Fungo version: 0.0.1

package reduce

func Reduce(items []string, calculation func(string, string) (string, error)) (string, error) {
	var acc string
	var err error
	for _, item := range items {
		acc, err = calculation(acc, item)
		if err != nil {
			return acc, err
		}
	}
	return acc, nil
}