// This source file was generated by Fungo. DO NOT MODIFY.
//
// Generated on: 2019-09-17 09:20:22
// Fungo version: 0.0.1

package min

import "errors"

func Min(items []int, comparison func(int, int) (int, error)) (int, error) {
	var min int
	if len(items) == 0 {
		return min, errors.New("slice contains no items")
	}
	min = items[0]
	for i := 1; i < len(items); i++ {
		res, err := comparison(items[i], min)
		if err != nil {
			return min, err
		}
		if res < 0 {
			min = items[i]
		}
	}
	return min, nil
}