// This source file was generated by Fungo. DO NOT MODIFY.
//
// Generated on: 2019-09-17 10:06:29
// Fungo version: 0.0.1

package contains

func Contains(list1 []string, list2 []string, predicate func(a string, b string) (bool, error)) (bool, int, error) {
	size1 := len(list1)
	size2 := len(list2)
	if (size1 == 0 || size2 == 0) || (size1 < size2) {
		return false, -1, nil
	}
	for i, _ := range list1 {
		bound := i + size2
		if bound > size1 {
			return false, -1, nil
		}
		slice := list1[i:bound]
		foundCount := 0
		for j, _ := range slice {
			result, err := predicate(slice[j], list2[j])
			if err != nil {
				return false, -1, err
			}
			if !result {
				break
			}
			foundCount++
			if foundCount == size2 {
				return true, i, nil
			}
		}
	}
	return false, -1, nil
}