// This source file was generated by Fungo. DO NOT MODIFY.
//
// Generated on: 2019-09-11 18:34:31
// Fungo version: 0.0.1

package all

func All(items []string, predicate func(string) (bool, error)) (bool, error) {
	for _, item := range items {
		res, err := predicate(item)
		if !res || err != nil {
			return false, err
		}
	}
	return true, nil
}