// This source file was generated by Fungo. DO NOT MODIFY.
//
// Generated on: 2019-09-17 10:06:29
// Fungo version: 0.0.1

package find_first

func FindFirst(items []string, predicate func(string) (bool, error)) (int, string, error) {
	for index, item := range items {
		res, err := predicate(item)
		if err != nil {
			return index, item, err
		}
		if res {
			return index, item, nil
		}
	}
	var emptyVal string
	return -1, emptyVal, nil
}